---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts":
    get:
      summary: Retrieve posts
      tags:
      - Posts
      parameters:
      - name: page
        in: query
        schema:
          type: string
      - name: per_page
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Posts found
          content:
            application/json:
              examples:
                default:
                  value:
                    posts:
                    - id: 280
                      kind: quoted
                      user_id: 217
                      username: one
                      quote: quote two
                      original_post_id: 278
                      original_content: content two
                      original_user_id: 218
                      original_username: two
                    - id: 279
                      kind: repost
                      user_id: 219
                      username: three
                      original_post_id: 277
                      original_content: content one
                      original_user_id: 217
                      original_username: one
                    - id: 278
                      kind: original
                      content: content two
                      user_id: 218
                      username: two
                    meta:
                      total: 4
                      page: 1
                      per_page: 3
        '400':
          description: Invalid params
          content:
            application/json:
              examples:
                invalid pagination:
                  value:
                    page:
                    - must be greater than or equal to 1
                    per_page:
                    - must be greater than or equal to 1
    post:
      summary: Create post
      tags:
      - Posts
      parameters: []
      responses:
        '201':
          description: Post created
          content:
            application/json:
              examples:
                original post:
                  value:
                    id: 281
                    kind: original
                    content: original content
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: string
                content:
                  type: string
                kind:
                  type: string
              required:
              - user_id
  "/api/v1/users/{id}":
    get:
      summary: Retrieve user profile
      tags:
      - User Profile
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User profile found
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 220
                    username: username
                    joined_at: March 25, 2021
        '400':
          description: Invalid param
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Invalid param
        '422':
          description: User not found
          content:
            application/json:
              examples:
                example:
                  value:
                    error: User not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
