---
openapi: 3.0.1
info:
  title: Posterr API V1
  version: v1
paths:
  "/api/v1/posts":
    get:
      summary: Retrieve posts
      tags:
      - Posts
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
      - name: per_page
        in: query
        required: false
        schema:
          type: string
      - name: user_id
        in: query
        required: false
        schema:
          type: string
      - name: start_date
        in: query
        required: false
        schema:
          type: string
      - name: end_date
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Posts found
          content:
            application/json:
              examples:
                all posts:
                  value:
                    posts:
                    - id: 343
                      kind: quoted
                      user_id: 112
                      username: one
                      quote: quote two
                      original_post_id: 341
                      original_content: content two
                      original_user_id: 113
                      original_username: two
                      posted_at: January 09, 2023
                    - id: 342
                      kind: repost
                      user_id: 114
                      username: three
                      original_post_id: 340
                      original_content: content one
                      original_user_id: 112
                      original_username: one
                      posted_at: January 09, 2023
                    - id: 341
                      kind: original
                      content: content two
                      user_id: 113
                      username: two
                      posted_at: January 09, 2023
                    meta:
                      total: 4
                      page: 1
                      per_page: 3
                filtered by user:
                  value:
                    posts:
                    - id: 347
                      kind: quoted
                      user_id: 99
                      username: one
                      quote: quote two
                      original_post_id: 345
                      original_content: content two
                      original_user_id: 115
                      original_username: two
                      posted_at: January 09, 2023
                    - id: 344
                      kind: original
                      content: content one
                      user_id: 99
                      username: one
                      posted_at: January 09, 2023
                    meta:
                      total: 2
                      page: 1
                      per_page: 3
                filterd by date:
                  value:
                    posts:
                    - id: 350
                      kind: original
                      content: Dolor totam sit. Aut et sed. Et ea ipsa.
                      user_id: 117
                      username: cliff.kemmer1
                      posted_at: July 18, 2021
                    - id: 349
                      kind: original
                      content: Debitis dolorem quam. Ipsam accusantium ratione. Molestias
                        dolores vero.
                      user_id: 117
                      username: cliff.kemmer1
                      posted_at: April 13, 2021
                    meta:
                      total: 2
                      page: 1
                      per_page: 3
        '400':
          description: Invalid params
          content:
            application/json:
              examples:
                invalid pagination:
                  value:
                    page:
                    - must be greater than or equal to 1
                    per_page:
                    - must be greater than or equal to 1
                invalid user id:
                  value:
                    user_id:
                    - must be greater than or equal to 1
                invalid date range:
                  value:
                    end_date:
                    - end date must be greater than start date
    post:
      summary: Create post
      tags:
      - Posts
      parameters: []
      responses:
        '201':
          description: Post created
          content:
            application/json:
              examples:
                original post:
                  value:
                    post:
                      id: 352
                      kind: original
                      content: original content
                repost:
                  value:
                    post:
                      id: 353
                      kind: repost
                      user_id: 98
                      original_post_id: 90
                quoted post:
                  value:
                    post:
                      id: 354
                      kind: quoted
                      user_id: 97
                      quote: some quote
                      original_post_id: 93
        '400':
          description: Invalid params
          content:
            application/json:
              examples:
                invalid kind:
                  value:
                    kind:
                    - is not included in the list
                    original_post_id:
                    - can't be blank
                missing content:
                  value:
                    content:
                    - can't be blank
                invalid content:
                  value:
                    content:
                    - is too long (maximum is 777 characters)
        '422':
          description: Unprocessable entity
          content:
            application/json:
              examples:
                user not found:
                  value:
                    user:
                    - user not found
                original post not found:
                  value:
                    original_post:
                    - original post not found
                can't repost a repost:
                  value:
                    original_post:
                    - can't be referenced by a post with the same kind
                can't quote a quoted post:
                  value:
                    original_post:
                    - can't be referenced by a post with the same kind
                post quota exceeded:
                  value:
                    post:
                    - post quota exceeded
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: string
                content:
                  type: string
                kind:
                  type: string
              required:
              - user_id
  "/api/v1/users/{user_id}/posts":
    get:
      summary: Retrieve the user posts
      tags:
      - User posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '302':
          description: Redirect
    post:
      summary: Create a post for the user
      tags:
      - User posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '302':
          description: Redirect
  "/api/v1/users/{id}":
    get:
      summary: Retrieve user profile
      tags:
      - User Profile
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User profile found
          content:
            application/json:
              examples:
                user profile:
                  value:
                    id: 118
                    username: username
                    joined_at: March 25, 2021
                    posts_count: 0
        '400':
          description: Invalid param
          content:
            application/json:
              examples:
                invalid user id:
                  value:
                    id:
                    - must be greater than or equal to 1
        '422':
          description: User not found
          content:
            application/json:
              examples:
                user not found:
                  value:
                    user:
                    - user not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
