---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts":
    get:
      summary: Retrieve posts
      tags:
      - Posts
      parameters:
      - name: page
        in: query
        schema:
          type: string
      - name: per_page
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Posts found
          content:
            application/json:
              examples:
                default:
                  value:
                    posts:
                    - id: 184
                      kind: quoted
                      user_id: 147
                      username: one
                      quote: quote two
                      original_post_id: 182
                      original_content: content two
                      original_user_id: 148
                      original_username: two
                    - id: 183
                      kind: repost
                      user_id: 149
                      username: three
                      original_post_id: 181
                      original_content: content one
                      original_user_id: 147
                      original_username: one
                    - id: 182
                      kind: original
                      content: content two
                      user_id: 148
                      username: two
                    meta:
                      total: 4
                      page: 1
                      per_page: 3
        '400':
          description: Invalid params
          content:
            application/json:
              examples:
                invalid pagination:
                  value:
                    page:
                    - must be greater than or equal to 1
                    per_page:
                    - must be greater than or equal to 1
  "/api/v1/users/{id}":
    get:
      summary: Retrieve user profile
      tags:
      - User Profile
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User profile found
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 150
                    username: username
                    joined_at: March 25, 2021
        '400':
          description: Invalid param
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Invalid param
        '422':
          description: User not found
          content:
            application/json:
              examples:
                example:
                  value:
                    error: User not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
